version: '3'
services:
  avaliacao-cast:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: avaliacao-cast
    ports:
      - '8080:8080'
      - '5005:5005'
    environment:
      - ADDITIONAL_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005 -Xmx1G -Xms128m -XX:MaxMetaspaceSize=128m
      - PROFILE=dev
    links:
      - db

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./docker/volume_mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=castgroup
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - SKIP-GRANT-TABLES=TRUE
